# Generated by Django 2.1.1 on 2018-10-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, help_text='Saber a data da criação da anotação ajudará a organizar seus trabalhos', verbose_name='Data da criação')),
                ('texto', models.TextField(help_text='Sua anotação vai aqui', verbose_name='Anotação')),
            ],
        ),
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Um nome descritivo ajudará a encontrar o caderno depois', max_length=50, verbose_name='Caderno')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Uma etiqueta para classificação/marcação da anotação. (ex.: 'Segunda Guerra', 'Xadrez')", max_length=50, verbose_name='Etiqueta')),
                ('cor', models.CharField(default='6A5ACD', help_text='A cor da etiqueta por ajudá-lo na classificação de suas anotações (use com sabedoria...)', max_length=6, verbose_name='Cor')),
            ],
        ),
        migrations.AddField(
            model_name='anotacao',
            name='caderno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nota.Caderno'),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='tag',
            field=models.ManyToManyField(help_text='Marque suas anotações para recuperá-las facilmente depois', to='nota.Etiqueta', verbose_name='Etiqueta'),
        ),
    ]
