# Generated by Django 2.1 on 2018-08-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="O nome natural do autor. (ex.: 'Aurelius Augustinus Hipponensis')", max_length=200, verbose_name='Nome')),
                ('pseudonimo', models.CharField(help_text="Pseudonimo, nome universal ou similar. (ex.: 'Santo Agostinho')", max_length=200, verbose_name='Nome')),
                ('nascimento', models.CharField(blank=True, help_text="Data de nascimento ou aproximações. (ex.: '354 d.C.')", max_length=50, null=True, verbose_name='Nascimento')),
                ('obito', models.CharField(blank=True, help_text="Data da morte ou aproximações. (ex.: '28/08/430')", max_length=50, null=True, verbose_name='Morte')),
                ('local_nascimento', models.CharField(blank=True, help_text='Local de nascimento.Sempre atualizar. (ex.: Província romana de Hipona, atual Annaba na Argélia)', max_length=50, null=True, verbose_name='Local de nascimento')),
                ('lingua_original', models.CharField(blank=True, help_text="Língua na qual o autor escreveu originalmente suas principais obras (ex.: 'Latim')", max_length=50, null=True, verbose_name='Língua original')),
                ('magni_opera', models.CharField(blank=True, help_text="Lista das maiores obras do autor (ex.: 'A cidade de Deus, Confissões')", max_length=200, null=True, verbose_name='Magni opera')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Titulo do livro (ex.: 'Confissões')", max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, help_text='Subtitulo do livro', max_length=200, null=True, verbose_name='Subtítulo')),
                ('edicao', models.CharField(blank=True, help_text='Número da edição (preencher mesmo que seja a primeira edição)', max_length=10, null=True, verbose_name='Edição')),
                ('local', models.CharField(blank=True, help_text="Informe o local da publicação. (ex.: 'Rio de Janeiro', 'Patos-PB')", max_length=50, null=True, verbose_name='Local da publicação')),
                ('editora', models.CharField(blank=True, help_text="Informe o nome da editora. (ex.: 'Cultrix')", max_length=50, null=True, verbose_name='Editora')),
                ('ano', models.CharField(blank=True, help_text="O ano da publicação, quando disponível (ex.: '1973', '198?' '1600?')", max_length=50, null=True, verbose_name='Ano da publicação')),
                ('colecao', models.CharField(blank=True, help_text="Este livro pertence a uma coleção? (ex.: 'Primeiros passos', 'O que é?')", max_length=50, null=True, verbose_name='Coleção')),
                ('volume', models.CharField(blank=True, help_text="O livro foi dividido em volumes? (ex.: 'Volume 1')", max_length=50, null=True, verbose_name='Volume')),
                ('sumario', models.TextField(blank=True, help_text='De que trata essa obra?', max_length=1500, null=True, verbose_name='Sumário')),
                ('autor', models.ManyToManyField(help_text='Indique o autor ou autores da obra', to='catalogo.Autor', verbose_name='Autoria')),
            ],
        ),
    ]
