# Generated by Django 2.1.1 on 2018-09-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
            ],
        ),
        migrations.CreateModel(
            name='PapelPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem de citação')),
                ('papel', models.CharField(choices=[('AUT', 'Autor'), ('TRA', 'Tradutor'), ('ORG', 'Organizador'), ('COO', 'Coordenador'), ('EDI', 'Editor'), ('REV', 'Revisor'), ('PRE', 'Prefaciador'), ('COM', 'Compilador'), ('ILU', 'Ilustrador')], default='AUT', max_length=3, verbose_name='Papel')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('pseudonimo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pseudônimo')),
                ('nascimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nascimento')),
                ('obito', models.CharField(blank=True, max_length=50, null=True, verbose_name='Morte')),
                ('local_nascimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Local de nascimento')),
                ('lingua_original', models.CharField(blank=True, max_length=50, null=True, verbose_name='Línguas utilizadas')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('fonte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.Fonte')),
                ('edicao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Edição')),
                ('local', models.CharField(blank=True, max_length=50, null=True, verbose_name='Local da publicação')),
                ('editora', models.CharField(blank=True, max_length=50, null=True, verbose_name='Editora')),
                ('ano', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ano da publicação')),
                ('paginas', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número de páginas')),
                ('colecao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coleção')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volume')),
            ],
            bases=('catalogo.fonte',),
        ),
        migrations.AddField(
            model_name='papelpessoa',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Fonte'),
        ),
        migrations.AddField(
            model_name='papelpessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Pessoa'),
        ),
        migrations.AddField(
            model_name='fonte',
            name='autor',
            field=models.ManyToManyField(through='catalogo.PapelPessoa', to='catalogo.Pessoa', verbose_name='Autoria'),
        ),
    ]
