# Generated by Django 2.1.1 on 2018-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='obito',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_obito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data do óbito'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='local_obito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local do óbito'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pseudonimo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pseudônimo ou Nome Universal'),
        ),
    ]
