# Generated by Django 2.1 on 2018-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='sobrenome',
            field=models.CharField(default='', help_text="O sobrenome ou nome familiar do autor. (ex.: 'Augustinus' em 'Aurelius Augustinus')", max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.CharField(blank=True, help_text='O número de páginas do livros. (consulte sempre a imprenta)', max_length=5, null=True, verbose_name='Número de páginas'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='lingua_original',
            field=models.CharField(blank=True, help_text="Línguas utilizadas pelo autor nas suas principais obras. (ex.: 'Latim')", max_length=50, null=True, verbose_name='Língua utilizadas'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(help_text="O primeiro nome do autor. (ex.: 'Aurelius' em 'Aurelius Augustinus')", max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(help_text="Pseudonimo ou nome universal do autor. (ex.: 'Santo Agostinho')", max_length=100, verbose_name='Pseudônimo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='colecao',
            field=models.CharField(blank=True, help_text="Indique o noem da coleção, se houver. (ex.: 'Primeiros passos', 'O que é?')", max_length=50, null=True, verbose_name='Coleção'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.CharField(blank=True, help_text='Número da edição (utilizar número arábico e preencher mesmo que seja a primeira edição)', max_length=10, null=True, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, default='', help_text='Subtitulo do livro', max_length=200, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sumario',
            field=models.TextField(blank=True, help_text='Breve descrição do conteúdo da obra (até 1500 caracteres).', max_length=1500, null=True, verbose_name='Sumário'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='volume',
            field=models.CharField(blank=True, help_text="Indique o número do volume, se houver mais de um (ex.: 'Volume 9')", max_length=50, null=True, verbose_name='Volume'),
        ),
    ]
