# Generated by Django 2.1.1 on 2018-09-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180927_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomePapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome do papel')),
                ('abreviatura', models.CharField(max_length=6, verbose_name='Abreviatura')),
                ('autoridade_fonte', models.BooleanField(default=False, verbose_name='Este papel é de autoridade da fonte?')),
            ],
        ),
    ]
