# Generated by Django 2.1 on 2018-09-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180901_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(blank=True, help_text="Pseudonimo ou nome universal do autor. (ex.: 'Santo Agostinho')", max_length=100, null=True, verbose_name='Pseudônimo'),
        ),
    ]
