# Generated by Django 2.1.1 on 2018-09-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_nomepapel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome do papel')),
                ('abreviatura', models.CharField(max_length=6, verbose_name='Abreviatura')),
                ('autoridade_fonte', models.BooleanField(default=False, verbose_name='Este papel é de autoridade da fonte?')),
            ],
        ),
        migrations.DeleteModel(
            name='NomePapel',
        ),
        migrations.AlterField(
            model_name='papelpessoa',
            name='papel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Papel'),
        ),
    ]
